M48
; DRILL file {KiCad 9.0.6} date 2026-02-23T11:27:53-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-23T11:27:53-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X205.27Y-87.71
T2
X164.56Y-86.81
X164.56Y-103.81
X217.56Y-86.81
X217.56Y-103.81
M30
